/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('antdv-next')['Alert']
    AApp: typeof import('antdv-next')['App']
    AAvatar: typeof import('antdv-next')['Avatar']
    AButton: typeof import('antdv-next')['Button']
    ACard: typeof import('antdv-next')['Card']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    ADropdown: typeof import('antdv-next')['Dropdown']
    AEmpty: typeof import('antdv-next')['Empty']
    AFlex: typeof import('antdv-next')['Flex']
    ALayout: typeof import('antdv-next')['Layout']
    ALayoutContent: typeof import('antdv-next')['LayoutContent']
    ALayoutHeader: typeof import('antdv-next')['LayoutHeader']
    ALayoutSider: typeof import('antdv-next')['LayoutSider']
    AMenu: typeof import('antdv-next')['Menu']
    AResult: typeof import('antdv-next')['Result']
    ATypographyText: typeof import('antdv-next')['TypographyText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
