/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('antdv-next')['Alert']
    AApp: typeof import('antdv-next')['App']
    AAutoComplete: typeof import('antdv-next')['AutoComplete']
    AAvatar: typeof import('antdv-next')['Avatar']
    ABreadcrumb: typeof import('antdv-next')['Breadcrumb']
    AButton: typeof import('antdv-next')['Button']
    ACard: typeof import('antdv-next')['Card']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    ADescriptions: typeof import('antdv-next')['Descriptions']
    ADescriptionsItem: typeof import('antdv-next')['DescriptionsItem']
    ADrawer: typeof import('antdv-next')['Drawer']
    ADropdown: typeof import('antdv-next')['Dropdown']
    AEmpty: typeof import('antdv-next')['Empty']
    AFlex: typeof import('antdv-next')['Flex']
    AForm: typeof import('antdv-next')['Form']
    AFormItem: typeof import('antdv-next')['FormItem']
    ALayout: typeof import('antdv-next')['Layout']
    ALayoutContent: typeof import('antdv-next')['LayoutContent']
    ALayoutHeader: typeof import('antdv-next')['LayoutHeader']
    ALayoutSider: typeof import('antdv-next')['LayoutSider']
    AMenu: typeof import('antdv-next')['Menu']
    AResult: typeof import('antdv-next')['Result']
    ASegmented: typeof import('antdv-next')['Segmented']
    ASelect: typeof import('antdv-next')['Select']
    ASkeleton: typeof import('antdv-next')['Skeleton']
    ASteps: typeof import('antdv-next')['Steps']
    ATable: typeof import('antdv-next')['Table']
    ATag: typeof import('antdv-next')['Tag']
    ATextarea: typeof import('antdv-next')['TextArea']
    ATypographyParagraph: typeof import('antdv-next')['TypographyParagraph']
    ATypographyText: typeof import('antdv-next')['TypographyText']
    CheckList: typeof import('./web/src/components/CheckList.vue')['default']
    PluginIcon: typeof import('./web/src/components/PluginIcon.vue')['default']
    PluginRow: typeof import('./web/src/components/PluginRow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiderNav: typeof import('./web/src/components/SiderNav.vue')['default']
  }
}
